### ISSUE TITLE
GetSmallestEnclosingRectangle() does not return the smallest rectangle

### ISSUE THREAD

**Issue by dsn27** [SOFAgh/CADability#116]
The function GetSmallestEnclosingRectangle() does not always return the smallest rectangle.

This triangle shaped form is 178.227 x 95.001 = 16,931.74² (Green rectangle)
The function returns 201.85 x 89.11 = 17,986.85² (Blue rectangle)

Is there anything we can do to improve the calculation?

[triangle.zip](https://github.com/SOFAgh/CADability/files/9921203/triangle.zip)
![grafik](https://user-images.githubusercontent.com/45662116/199513407-3b11e50d-6368-4c91-b676-c3c6db71aa8c.png)

**Comment by SOFAgh** [comment]
GetSmallestEnclosingRectangle() is pretty simple: it uses the convex hull of the border, then it takes each line as a basis direction and calculates the extent. It should be simple to debug.

**Comment by dsn27** [comment]
Close #119
