### ISSUE TITLE
Get Volumen Information of Solid

### ISSUE THREAD

**Issue by MichaelHilgers** [SOFAgh/CADability#12]
Set Volumen Property of solid

![image](https://user-images.githubusercontent.com/12812984/98656967-9c79b380-2341-11eb-83ff-565353e11dab.png)

**Comment by SOFAgh** [comment]
Solid.Volume implemented. 
`public double Volume(double precision)`
"precision" refers to a triangulation, if 0.0 uses the currently available triangulation. For solids with only planar faces, precision doesn't make a difference.
