### ISSUE TITLE
ImportStep does not respect unit

### ISSUE THREAD

**Issue by Steinblock** [SOFAgh/CADability#153]
I have a simple step file and CADability shows the width and height as 0.38 and 0.8.

<img width="434" alt="image" src="https://github.com/SOFAgh/CADability/assets/6850324/411577b6-1f5b-4ca9-9889-9cc4a7a424bb">

However the part has been constructed in Autodesk Inventor 2023 and saved with unit meter. Other step viewers show the correct size of 380 and 800.

Here is the file for reference.

[simple-part-mm.zip](https://github.com/SOFAgh/CADability/files/12077106/simple-part-mm.zip)

**Comment by dsn27** [comment]
It seems like the unit is not read under all circumstances.
While there is code that is trying to figure out the units, this does not seem to work for this file.
e.g.
https://github.com/SOFAgh/CADability/blob/e6794d6730d618307e2a8d8c5f34f6fbe7d97719/CADability/ImportStep.cs#L4757-L4782

https://github.com/SOFAgh/CADability/blob/e6794d6730d618307e2a8d8c5f34f6fbe7d97719/CADability/ImportStep.cs#L4804-L4825

**Comment by dsn27** [comment]
Closed by #182
