### ISSUE TITLE
NullReferenceException in GeoPointProperty.InitFormat

### ISSUE THREAD

**Issue by dsn27** [SOFAgh/CADability#20]
A System.NullReferenceException is thrown after a Polyline is selected.

frame is null
`numberFormatInfo.NumberDecimalDigits = frame.GetIntSetting("Formatting.Coordinate.Digits", 3);`

`System.NullReferenceException
  HResult=0x80004003
  Message=Der Objektverweis wurde nicht auf eine Objektinstanz festgelegt.
  Source=CADability
  StackTrace:
   at CADability.UserInterface.GeoPointProperty.InitFormat(IFrame frame) in C:\Development\Repos\SOFAgh\CADability\CADability\GeoPointProperty.cs:line 122
`

Full call stack:
`CADability.dll!CADability.UserInterface.GeoPointProperty.InitFormat(CADability.IFrame frame) Line 122	C#
CADability.dll!CADability.UserInterface.GeoPointProperty.GeoPointProperty(CADability.IFrame frame, string resourceId) Line 101	C#
CADability.dll!CADability.UserInterface.GeoPointProperty.GeoPointProperty(string resourceId, CADability.IFrame frame, bool autoModifyWithMouse) Line 417	C#
CADability.dll!CADability.UserInterface.MultiGeoPointProperty.SubItems.get() Line 227	C#
CADability.dll!CADability.UserInterface.PropertyEntryImpl.SubEntries.get() Line 269	C#
CADability.dll!CADability.UserInterface.ShowPropertyPolyline.OnVertexPropertyStateChanged(CADability.UserInterface.IPropertyEntry sender, CADability.UserInterface.StateChangedArgs args) Line 596	C#
CADability.dll!CADability.UserInterface.PropertyEntryImpl.PropertyEntryChangedState(CADability.UserInterface.StateChangedArgs args) Line 33	C#
CADability.dll!CADability.UserInterface.PropertyEntryImpl.Opened(bool isOpen) Line 180	C#
CADability.dll!CADability.UserInterface.PropertyEntryImpl.IsOpen.set(bool value) Line 64	C#
CADability.dll!CADability.UserInterface.PropertyEntryImpl.OpenOrCloseSubEntries() Line 205	C#
CADability.Forms.dll!CADability.Forms.PropertyPage.OpenSubEntries(CADability.UserInterface.IPropertyEntry toOpenOrClose, bool open) Line 775	C#
CADability.dll!CADability.UserInterface.ShowPropertyPolyline.Opened(bool IsOpen) Line 625	C#
CADability.dll!CADability.UserInterface.IShowPropertyImpl.CADability.UserInterface.IPropertyEntry.IsOpen.set(bool value) Line 703	C#
CADability.dll!CADability.UserInterface.IShowPropertyImpl.OpenOrCloseSubEntries() Line 756	C#
CADability.Forms.dll!CADability.Forms.PropertyPage.OpenSubEntries(CADability.UserInterface.IPropertyEntry toOpenOrClose, bool open) Line 775	C#
CADability.dll!CADability.UserInterface.SelectedObjectsProperty.OpenSubEntries() Line 521	C#
CADability.dll!CADability.Actions.SelectObjectsAction.AddSelectedObjects(CADability.GeoObject.GeoObjectList selObj) Line 770	C#
CADability.dll!CADability.Actions.SelectObjectsAction.SetSelectedObjects(CADability.GeoObject.GeoObjectList selObj) Line 813	C#
CADability.dll!CADability.Actions.SelectObjectsAction.OnMouseUp(CADability.Substitutes.MouseEventArgs e, CADability.IView vw) Line 1489	C#
CADability.dll!CADability.ActionStack.OnMouseUp(CADability.Substitutes.MouseEventArgs e, CADability.IView View) Line 328	C#
CADability.dll!CADability.ModelView.CADability.IView.OnMouseUp(CADability.Substitutes.MouseEventArgs eIn) Line 1135	C#
CADability.Forms.dll!CADability.Forms.CadCanvas.OnMouseUp(System.Windows.Forms.MouseEventArgs e) Line 244	C#
[External Code]	
CADability.App.exe!CADability.App.Program.Main(string[] args) Line 19	C#`

**Comment by SOFAgh** [comment]
probably fixed meanwhile
