### ISSUE TITLE
Incorrect drawing of Polyline when create a new one

### ISSUE THREAD

**Issue by dsn27** [SOFAgh/CADability#23]
While creating a new Polyline the lines drawn on the Canvas are one vertex behind.
You can see on the right side on the control center that a new point is created. But the canvas is updated only after the next point is clicked.

![11-02-_2021_09-25-41](https://user-images.githubusercontent.com/45662116/107615109-e24d5d00-6c4b-11eb-9b3f-ec92822a1552.gif)

**Comment by SOFAgh** [comment]
fixed

**Comment by SOFAgh** [comment]
fixed
