### ISSUE TITLE
Context menus are missing

### ISSUE THREAD

**Issue by dsn27** [SOFAgh/CADability#28]
The context menus contain only dummy entries.

Didn't this work before?

![grafik](https://user-images.githubusercontent.com/45662116/112150654-a01b2200-8be0-11eb-903b-a39f81d405c5.png)

**Comment by SOFAgh** [comment]
Remove the conditional compilation symbol "TESTNEWCONTEXTMENU". This is experimental and was accidentally defined in the latest update
