### ISSUE TITLE
GaussNewtonMinimizer 'cube' does not exist in Release mode

### ISSUE THREAD

**Issue by dsn27** [SOFAgh/CADability#31]
Line 2015 `static private double cube(double x) { return x * x * x; }`
is excluded in Release mode but it is needed by various functions

e.g. Line 415 `double sc8 = cube(b) * sc11;`

The program can not be compiled.
Error	CS0103	The name 'cube' does not exist in the current context	CADability	C:\Development\Repos\SOFAgh\CADability\CADability\GaussNewtonMinimizer.cs	415

**Comment by SOFAgh** [comment]
fixed
