### ISSUE TITLE
Ruled Surface display problem

### ISSUE THREAD

**Issue by happydpc** [SOFAgh/CADability#61]
Create a ruled-surface with two rectanges:

### CADability
![image](https://user-images.githubusercontent.com/771776/148364613-db090b3c-7e2b-4526-8158-6e68386a389c.png)

### FreeCAD
![image](https://user-images.githubusercontent.com/771776/148364648-09ccf31c-5b7a-4276-8821-567ec98f9288.png)

**Comment by SOFAgh** [comment]
Thank you!
Found and fixed the bug. Will be merged into the master branch
![Ruled](https://user-images.githubusercontent.com/37174533/148409234-22ba3240-6448-4dea-9100-24d0b0da4d58.png)
The bugfix is already in the branch "ParallelStepImport", which will be merged into the master branch later.
