### ISSUE TITLE
Holes are at a wrong position after DXF import.

### ISSUE THREAD

**Issue by Steinblock** [SOFAgh/CADability#98]
This simple file (dxf) [square_with_reduction.zip](https://github.com/SOFAgh/CADability/files/9755966/square_with_reduction.zip)

This is how the file should look like:

![image](https://user-images.githubusercontent.com/6850324/195095861-c632ee71-fdf4-4855-aafd-9cc11eb7f727.png)

And this is how it looks in CADability:

![image](https://user-images.githubusercontent.com/6850324/195096585-30df2147-891e-4dcd-8110-61a2f3428aec.png)

The issue is probably because the reference point is not zero based (if I move the botto right corner to 0,0 the position is correct).

(PR to fix this follows)

**Comment by dsn27** [comment]
Closed by #99
